version: '3.8'

services:
  backend:
    build: ./meme-soundboard-backend
    ports:
      - "3000:3000"
    volumes:
      - ./meme-soundboard-backend:/app
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 